version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build_container
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
    command: /rust_build/target/release/chat_app
    ports:
      - 8000:8000
    expose:
      - 8000

  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
